### ISSUE TITLE
Django 3 missing templatetag staticfiles

### ISSUE THREAD

**Issue by jayvdb** [barseghyanartur/django-admin-timeline#16]
Probably the last Django 3 'critical' problem

```py
Internal Server Error: /admin/timeline/
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/template/defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'
```

referring to https://github.com/barseghyanartur/django-admin-timeline/blob/26a94fc97e6d0461420cae9feb5342ee4ce2b08b/src/admin_timeline/templates/admin_timeline/timeline.html

**Comment by barseghyanartur** [comment]
Released in 1.8.
