### ISSUE TITLE
Not working on django 1.10

### ISSUE THREAD

**Issue by RamizSami** [barseghyanartur/django-admin-timeline#4]
The following line in views.py is not working:
return render_to_response(
        template_name, context, context_instance=RequestContext(request)
        )
please update it to:
return render(request, template_name, context)

It will work in django 1.10 then

**Comment by barseghyanartur** [comment]
@RamizSami:

Correct. It's not yet compatible with Django 1.9 and 1.10. I've added it to the milestone, although not sure when it will be done.

**Comment by RamizSami** [comment]
I've made it work with django 1.10. Just replace the above mentioned lines and it will work.

**Comment by barseghyanartur** [comment]
@RamizSami:

Solved in 1.6.
