### ISSUE TITLE
How to change the admin title in admin-timeline?

### ISSUE THREAD

**Issue by RamizSami** [barseghyanartur/django-admin-timeline#5]
Also, is there any way to add in any other admin skin?

**Comment by barseghyanartur** [comment]
@RamizSami:

You can override the [admin_timeline/timeline.html](https://github.com/barseghyanartur/django-admin-timeline/blob/master/src/admin_timeline/templates/admin_timeline/timeline.html) template, override the [admin_timeline/css/admin_timeline.css](https://github.com/barseghyanartur/django-admin-timeline/blob/master/src/admin_timeline/static/admin_timeline/css/admin_timeline.css) CSS.

**Comment by RamizSami** [comment]
Okay thanks
